services:
  causal-nest:
    image: gfviegas/causal-nest
    platform: linux/amd64
    build:
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "5555:5555"
    tty: true
    volumes:
      - ./:/app
    # command: "poetry run jupyter notebook --no-browser --ip 0.0.0.0 --port 8080 --allow-root"
    command: "poetry run python3 grpc_interface/server.py"
    # command: "python -m grpc_interface.server"
    networks:
      - network1

networks:
  network1:
    name: ciw_backend_default
    external: true
